// Codegen: regenerate src/paths-index.ts from src/paths/*.ts, then gate on
// spec compilation + fixture-probed collisions. Static imports keep the
// module graph knowable for `bun build --compile`. pi never edits the index —
// it only adds files under src/paths/; this script runs before every build.
import { readdirSync } from "node:fs"
import { join } from "node:path"

const ROOT = join(import.meta.dir, "..")
const PATHS_DIR = join(ROOT, "src", "paths")
const INDEX = join(ROOT, "src", "paths-index.ts")

const files = readdirSync(PATHS_DIR)
	.filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
	.sort()

const ident = (f: string) => "p_" + f.replace(/\.ts$/, "").replace(/[^a-zA-Z0-9]/g, "_")

const src =
	"// GENERATED by scripts/gen.ts — do not edit; run `bun run gen`.\n" +
	files.map((f) => `import ${ident(f)} from "./paths/${f.replace(/\.ts$/, "")}"`).join("\n") +
	'\nimport type { Path } from "./core"\n\n' +
	`export const paths: Path[] = [\n${files.map((f) => `\t${ident(f)},`).join("\n")}\n]\n`

await Bun.write(INDEX, src)
console.log(`paths-index.ts: ${files.length} paths`)

// gate: specs must compile, names unique, fixtures must dispatch uniquely
const { paths } = await import(INDEX)
const { checkCollisions, compileSpec } = await import(join(ROOT, "src", "core.ts"))

const problems: string[] = []
const names = new Set<string>()
for (const p of paths) {
	if (names.has(p.name)) problems.push(`DUPLICATE NAME ${p.name}`)
	names.add(p.name)
	try {
		compileSpec(p.spec)
	} catch (e) {
		problems.push(`BAD SPEC ${p.name}: ${e}`)
	}
	if (!p.fixtures.length) problems.push(`NO FIXTURES ${p.name} (fixtures double as collision probes)`)
}
problems.push(...checkCollisions(paths))

if (problems.length) {
	console.error("codegen gate FAILED:")
	for (const p of problems) console.error("  " + p)
	process.exit(1)
}
console.log("codegen gate: ok")
