// GENERATED by scripts/gen.ts — do not edit; run `bun run gen`.
import p_add from "./paths/add"
import p_branch_create from "./paths/branch-create"
import p_branch_delete from "./paths/branch-delete"
import p_branch_list_pattern from "./paths/branch-list-pattern"
import p_branch_list from "./paths/branch-list"
import p_branch_move from "./paths/branch-move"
import p_branch_no_color_no_column_remotes from "./paths/branch-no-color-no-column-remotes"
import p_branch_no_color_no_column from "./paths/branch-no-color-no-column"
import p_branch_set_upstream from "./paths/branch-set-upstream"
import p_branch_show_current from "./paths/branch-show-current"
import p_check_ignore_z_stdin from "./paths/check-ignore-z-stdin"
import p_check_ignore from "./paths/check-ignore"
import p_check_ref_format_refname from "./paths/check-ref-format-refname"
import p_check_ref_format from "./paths/check-ref-format"
import p_checkout_branch from "./paths/checkout-branch"
import p_checkout_paths from "./paths/checkout-paths"
import p_clean from "./paths/clean"
import p_commit from "./paths/commit"
import p_config_get_null from "./paths/config-get-null"
import p_config_list from "./paths/config-list"
import p_config_name_only_get_regexp from "./paths/config-name-only-get-regexp"
import p_config_replace_all from "./paths/config-replace-all"
import p_config_unset_all from "./paths/config-unset-all"
import p_config from "./paths/config"
import p_diff_cached_name_status from "./paths/diff-cached-name-status"
import p_diff_cached_numstat from "./paths/diff-cached-numstat"
import p_diff_name_status from "./paths/diff-name-status"
import p_diff_no_ext_diff_cached_patch_minimal from "./paths/diff-no-ext-diff-cached-patch-minimal"
import p_diff_numstat from "./paths/diff-numstat"
import p_diff_patch_minimal_ignore_all_space_range from "./paths/diff-patch-minimal-ignore-all-space-range"
import p_diff_patch_minimal_ignore_all_space from "./paths/diff-patch-minimal-ignore-all-space"
import p_diff_patch_minimal from "./paths/diff-patch-minimal"
import p_diff_prose from "./paths/diff-prose"
import p_fetch from "./paths/fetch"
import p_for_each_ref_committerdate from "./paths/for-each-ref-committerdate"
import p_for_each_ref_multi_pattern from "./paths/for-each-ref-multi-pattern"
import p_for_each_ref_remotes from "./paths/for-each-ref-remotes"
import p_for_each_ref_sorted from "./paths/for-each-ref-sorted"
import p_for_each_ref from "./paths/for-each-ref"
import p_log_cherry_mark_right_only from "./paths/log-cherry-mark-right-only"
import p_log_format from "./paths/log-format"
import p_log_no_merges_format from "./paths/log-no-merges-format"
import p_log_plain from "./paths/log-plain"
import p_ls_files_error_unmatch from "./paths/ls-files-error-unmatch"
import p_ls_files_others_exclude_standard from "./paths/ls-files-others-exclude-standard"
import p_ls_files from "./paths/ls-files"
import p_ls_remote_heads from "./paths/ls-remote-heads"
import p_merge_base_is_ancestor from "./paths/merge-base-is-ancestor"
import p_merge_base from "./paths/merge-base"
import p_mv from "./paths/mv"
import p_pull from "./paths/pull"
import p_push from "./paths/push"
import p_remote_get_url_push from "./paths/remote-get-url-push"
import p_remote_get_url from "./paths/remote-get-url"
import p_remote from "./paths/remote"
import p_reset from "./paths/reset"
import p_restore_staged from "./paths/restore-staged"
import p_restore_worktree from "./paths/restore-worktree"
import p_rev_list_count from "./paths/rev-list-count"
import p_rev_parse_abbrev_ref_symbolic_full_name from "./paths/rev-parse-abbrev-ref-symbolic-full-name"
import p_rev_parse_abbrev_ref from "./paths/rev-parse-abbrev-ref"
import p_rev_parse_git_common_dir from "./paths/rev-parse-git-common-dir"
import p_rev_parse_git_dir_git_paths from "./paths/rev-parse-git-dir-git-paths"
import p_rev_parse_git_dir from "./paths/rev-parse-git-dir"
import p_rev_parse_git_path from "./paths/rev-parse-git-path"
import p_rev_parse_is_bare_repository from "./paths/rev-parse-is-bare-repository"
import p_rev_parse_is_inside_work_tree from "./paths/rev-parse-is-inside-work-tree"
import p_rev_parse_rev from "./paths/rev-parse-rev"
import p_rev_parse_short from "./paths/rev-parse-short"
import p_rev_parse_show_toplevel from "./paths/rev-parse-show-toplevel"
import p_rev_parse_toplevel_common_dir from "./paths/rev-parse-toplevel-common-dir"
import p_rev_parse_toplevel_git_dir_abbrev_ref from "./paths/rev-parse-toplevel-git-dir-abbrev-ref"
import p_rev_parse_verify from "./paths/rev-parse-verify"
import p_show_blob from "./paths/show-blob"
import p_show_commit from "./paths/show-commit"
import p_show_ref_verify from "./paths/show-ref-verify"
import p_stash from "./paths/stash"
import p_status_long from "./paths/status-long"
import p_status_porcelain_2 from "./paths/status-porcelain-2"
import p_status_porcelain_v1_z_renames from "./paths/status-porcelain-v1-z-renames"
import p_status_porcelain_v1_z from "./paths/status-porcelain-v1-z"
import p_status_porcelain_v1 from "./paths/status-porcelain-v1"
import p_status_porcelain_v2 from "./paths/status-porcelain-v2"
import p_status_sb from "./paths/status-sb"
import p_switch from "./paths/switch"
import p_symbolic_ref_head from "./paths/symbolic-ref-head"
import p_symbolic_ref_remote_head from "./paths/symbolic-ref-remote-head"
import p_unsupported_clone from "./paths/unsupported-clone"
import p_unsupported_commit_tree from "./paths/unsupported-commit-tree"
import p_unsupported_read_tree from "./paths/unsupported-read-tree"
import p_unsupported_remote_mutate from "./paths/unsupported-remote-mutate"
import p_unsupported_submodule from "./paths/unsupported-submodule"
import p_unsupported_update_ref from "./paths/unsupported-update-ref"
import p_unsupported_write_tree from "./paths/unsupported-write-tree"
import p_worktree_add from "./paths/worktree-add"
import p_worktree_flag_list from "./paths/worktree-flag-list"
import p_worktree_list from "./paths/worktree-list"
import p_worktree_prune from "./paths/worktree-prune"
import p_worktree_remove from "./paths/worktree-remove"
import type { Path } from "./core"

export const paths: Path[] = [
	p_add,
	p_branch_create,
	p_branch_delete,
	p_branch_list_pattern,
	p_branch_list,
	p_branch_move,
	p_branch_no_color_no_column_remotes,
	p_branch_no_color_no_column,
	p_branch_set_upstream,
	p_branch_show_current,
	p_check_ignore_z_stdin,
	p_check_ignore,
	p_check_ref_format_refname,
	p_check_ref_format,
	p_checkout_branch,
	p_checkout_paths,
	p_clean,
	p_commit,
	p_config_get_null,
	p_config_list,
	p_config_name_only_get_regexp,
	p_config_replace_all,
	p_config_unset_all,
	p_config,
	p_diff_cached_name_status,
	p_diff_cached_numstat,
	p_diff_name_status,
	p_diff_no_ext_diff_cached_patch_minimal,
	p_diff_numstat,
	p_diff_patch_minimal_ignore_all_space_range,
	p_diff_patch_minimal_ignore_all_space,
	p_diff_patch_minimal,
	p_diff_prose,
	p_fetch,
	p_for_each_ref_committerdate,
	p_for_each_ref_multi_pattern,
	p_for_each_ref_remotes,
	p_for_each_ref_sorted,
	p_for_each_ref,
	p_log_cherry_mark_right_only,
	p_log_format,
	p_log_no_merges_format,
	p_log_plain,
	p_ls_files_error_unmatch,
	p_ls_files_others_exclude_standard,
	p_ls_files,
	p_ls_remote_heads,
	p_merge_base_is_ancestor,
	p_merge_base,
	p_mv,
	p_pull,
	p_push,
	p_remote_get_url_push,
	p_remote_get_url,
	p_remote,
	p_reset,
	p_restore_staged,
	p_restore_worktree,
	p_rev_list_count,
	p_rev_parse_abbrev_ref_symbolic_full_name,
	p_rev_parse_abbrev_ref,
	p_rev_parse_git_common_dir,
	p_rev_parse_git_dir_git_paths,
	p_rev_parse_git_dir,
	p_rev_parse_git_path,
	p_rev_parse_is_bare_repository,
	p_rev_parse_is_inside_work_tree,
	p_rev_parse_rev,
	p_rev_parse_short,
	p_rev_parse_show_toplevel,
	p_rev_parse_toplevel_common_dir,
	p_rev_parse_toplevel_git_dir_abbrev_ref,
	p_rev_parse_verify,
	p_show_blob,
	p_show_commit,
	p_show_ref_verify,
	p_stash,
	p_status_long,
	p_status_porcelain_2,
	p_status_porcelain_v1_z_renames,
	p_status_porcelain_v1_z,
	p_status_porcelain_v1,
	p_status_porcelain_v2,
	p_status_sb,
	p_switch,
	p_symbolic_ref_head,
	p_symbolic_ref_remote_head,
	p_unsupported_clone,
	p_unsupported_commit_tree,
	p_unsupported_read_tree,
	p_unsupported_remote_mutate,
	p_unsupported_submodule,
	p_unsupported_update_ref,
	p_unsupported_write_tree,
	p_worktree_add,
	p_worktree_flag_list,
	p_worktree_list,
	p_worktree_prune,
	p_worktree_remove,
]
